version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: chen
      MONGO_INITDB_ROOT_PASSWORD: chen
    ports:
      - 27017:27017

  messagepush-server:
    image: jimchen8889/messagepush:latest
    restart: always
    ports:
      - 5000:80
    depends_on:
      - mongo